# SPDX-License-Identifier: Apache-2.0
blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/lamawithonel/lamadist/discussions
    about: Ask questions or start a discussion
